/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ma.ac.emi.simplesoftphone.ui;

import ma.ac.emi.simplesoftphone.sip.SipLink;

import javax.sip.InvalidArgumentException;
import javax.sound.sampled.*;
import javax.swing.*;
import java.io.File;
import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;

/**
 * @author Joel
 */
public class SipPhone extends JFrame implements SipCall {

    private SipLink link;
    private String calleeAddress;
    private boolean establishing = false;
    private boolean ringing = false;
    private boolean calling = false;

    private Clip clip;

    private static final String RINGING_MEDIA = "assets/ringing.wav";
    private static final String RINGTONE_MEDIA = "assets/ringtone.wav";

    /**
     * Creates new form SipBasicPhone
     */
    public SipPhone() {
        initComponents();
        String ip = "0.0.0.0"; // Adresse Ip locale
        try {
            ip = InetAddress.getLocalHost().getHostAddress();
        } catch (UnknownHostException e) {
            e.printStackTrace();
        }

        localRtpAddressIpTextField.setText(ip);
        localSipAddressIpTextField.setText(ip);
        destRtpAddressIpTextField.setText(ip);
        destSipAddressIpTextField.setText(ip);
        proxySipAddressIpTextField.setText(ip);
        divertSipAddressIpTextField.setText(ip);

        /*try {

            link = new SipLink(ip,
                    Integer.parseInt(localSipAddressPortTextField.getText()),
                    Integer.parseInt(localRtpAddressPortTextField.getText()),
                    this);
            disableConfiguration();
        } catch (InvalidArgumentException e) {
            enableConfiguration();
            callButton.setEnabled(false);
        }*/
        // DEBUG
        while (true) {
            try {

                link = new SipLink(ip,
                        Integer.parseInt(localSipAddressPortTextField.getText()),
                        Integer.parseInt(localRtpAddressPortTextField.getText()),
                        this);
                disableConfiguration();
                break;
            } catch (InvalidArgumentException e) {
                localSipAddressPortTextField.setText(String.valueOf(Integer.parseInt(localSipAddressPortTextField.getText()) + 1));
                localRtpAddressPortTextField.setText(String.valueOf(Integer.parseInt(localRtpAddressPortTextField.getText()) + 1));
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        callActionsPanel = new javax.swing.JPanel();
        incomingCallPanel = new javax.swing.JPanel();
        callingPanel = new javax.swing.JPanel();
        callPanel = new javax.swing.JPanel();
        callButton = new javax.swing.JButton();
        hangupButton = new javax.swing.JButton();
        endCallButton = new javax.swing.JButton();
        takeCallButton = new javax.swing.JButton();
        incomingCallContentLabel = new javax.swing.JLabel();
        callingContentLabel = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        callActionsPanel = new javax.swing.JPanel();
        callPanel = new javax.swing.JPanel();
        callButton = new javax.swing.JButton();
        contentLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        destSipAddressIpTextField = new javax.swing.JTextField();
        destSipAddressPortTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        destRtpAddressIpTextField = new javax.swing.JTextField();
        destRtpAddressPortTextField = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        registerServiceButton = new javax.swing.JButton();
        cancelServiceButton = new javax.swing.JButton();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        divertSipAddressIpTextField = new javax.swing.JTextField();
        divertSipAddressPortTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        divertConditionComboBox = new javax.swing.JComboBox<>();
        jPanel20 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        proxyRegisterButton = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        numberTextField = new javax.swing.JTextField();
        callNumberTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        configureButton = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        localSipAddressIpTextField = new javax.swing.JTextField();
        localSipAddressPortTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        localRtpAddressIpTextField = new javax.swing.JTextField();
        localRtpAddressPortTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        proxySipAddressIpTextField = new javax.swing.JTextField();
        proxySipAddressPortTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        receivedMessagesTextArea = new javax.swing.JTextArea();
        jPanel18 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sentMessagesTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        callActionsPanel.setLayout(new java.awt.BorderLayout());

        callButton.setText("Appeler");
        callButton.addActionListener(evt -> call());

        hangupButton.setText("Racrocher");
        hangupButton.addActionListener(evt -> hangUp());

        endCallButton.setText("Racrocher");
        endCallButton.addActionListener(evt -> hangUp());

        takeCallButton.setText("Décrocher");
        takeCallButton.addActionListener(evt -> takeCall());

        javax.swing.GroupLayout callPanelLayout = new javax.swing.GroupLayout(callPanel);
        callPanel.setLayout(callPanelLayout);
        callPanelLayout.setHorizontalGroup(
                callPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, callPanelLayout.createSequentialGroup()
                                .addContainerGap(302, Short.MAX_VALUE).addComponent(callButton)
                                .addContainerGap())
        );
        callPanelLayout.setVerticalGroup(
                callPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, callPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(callButton)
                                .addContainerGap())
        );


        callActionsPanel.add(callPanel, java.awt.BorderLayout.PAGE_END);

        incomingCallContentLabel.setText("");

        javax.swing.GroupLayout incomingCallPanelLayout = new javax.swing.GroupLayout(incomingCallPanel);
        incomingCallPanel.setLayout(incomingCallPanelLayout);
        incomingCallPanelLayout.setHorizontalGroup(
                incomingCallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, incomingCallPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(incomingCallContentLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                                .addComponent(hangupButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(takeCallButton)
                                .addContainerGap())
        );
        incomingCallPanelLayout.setVerticalGroup(
                incomingCallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, incomingCallPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(incomingCallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(takeCallButton)
                                        .addComponent(hangupButton)
                                        .addComponent(incomingCallContentLabel))
                                .addContainerGap())
        );

        callingContentLabel.setText("");

        javax.swing.GroupLayout callingPanelLayout = new javax.swing.GroupLayout(callingPanel);
        callingPanel.setLayout(callingPanelLayout);
        callingPanelLayout.setHorizontalGroup(
                callingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, callingPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(callingContentLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                                .addComponent(endCallButton)
                                .addContainerGap())
        );
        callingPanelLayout.setVerticalGroup(
                callingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, callingPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(callingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(endCallButton)
                                        .addComponent(callingContentLabel))
                                .addContainerGap())
        );

        jPanel7.setLayout(new java.awt.GridLayout(3, 2));

        jLabel13.setText("Numéro :");
        jPanel7.add(jLabel13);

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
                jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(callNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
                jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel31Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(callNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel31);

        jLabel1.setText("Adresse SIP du destinataire :");
        jPanel7.add(jLabel1);

        destSipAddressIpTextField.setToolTipText("IP");

        destSipAddressPortTextField.setText("6060");
        destSipAddressPortTextField.setToolTipText("Port");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(destSipAddressIpTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(destSipAddressPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(destSipAddressIpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(destSipAddressPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        jPanel7.add(jPanel8);

        jLabel2.setText("Adresse RTP du destinataire :");
        jPanel7.add(jLabel2);

        destRtpAddressPortTextField.setText("10000");
        destRtpAddressPortTextField.setToolTipText("Port");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(destRtpAddressIpTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(destRtpAddressPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(destRtpAddressIpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(destRtpAddressPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel9);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        callActionsPanel.add(jPanel6, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(callActionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(callActionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Appel", jPanel1);

        jPanel25.setLayout(new java.awt.BorderLayout());

        registerServiceButton.setText("Enregistrer");
        registerServiceButton.addActionListener(evt -> registerService());

        cancelServiceButton.setText("Annuler");
        cancelServiceButton.addActionListener(evt -> cancelService());
        cancelServiceButton.setEnabled(false);

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
                jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                                .addContainerGap(218, Short.MAX_VALUE)
                                .addComponent(cancelServiceButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(registerServiceButton)
                                .addContainerGap())
        );
        jPanel26Layout.setVerticalGroup(
                jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(registerServiceButton)
                                        .addComponent(cancelServiceButton))
                                .addContainerGap())
        );

        jPanel25.add(jPanel26, java.awt.BorderLayout.PAGE_END);

        jPanel28.setLayout(new java.awt.GridLayout(2, 2));

        jLabel9.setText("Adresse SIP déviation :");
        jPanel28.add(jLabel9);

        divertSipAddressIpTextField.setToolTipText("IP");
        divertSipAddressPortTextField.setText("6060");
        divertSipAddressPortTextField.setToolTipText("Port");

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
                jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel29Layout.createSequentialGroup()
                                .addComponent(divertSipAddressIpTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(divertSipAddressPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel29Layout.setVerticalGroup(
                jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel29Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(divertSipAddressIpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(divertSipAddressPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        jPanel28.add(jPanel29);

        jLabel10.setText("Condition : ");
        jPanel28.add(jLabel10);

        divertConditionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Sans condition", "Si occupé"}));
        //divertConditionComboBox.setEnabled(false);

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
                jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel30Layout.createSequentialGroup()
                                .addComponent(divertConditionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 61, Short.MAX_VALUE))
        );
        jPanel30Layout.setVerticalGroup(
                jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel30Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(divertConditionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        jPanel28.add(jPanel30);

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
                jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel27Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel27Layout.setVerticalGroup(
                jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel27Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(148, Short.MAX_VALUE))
        );

        jPanel25.add(jPanel27, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Déviation d'appel", jPanel25);

        jPanel20.setLayout(new java.awt.BorderLayout());

        proxyRegisterButton.setText("Enregistrer");
        proxyRegisterButton.addActionListener(evt -> register());


        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
                jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                                .addContainerGap(298, Short.MAX_VALUE)
                                .addComponent(proxyRegisterButton)
                                .addContainerGap())
        );

        jPanel21Layout.setVerticalGroup(
                jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(proxyRegisterButton)
                                .addContainerGap())
        );

        jPanel20.add(jPanel21, java.awt.BorderLayout.PAGE_END);

        jPanel23.setLayout(new java.awt.GridLayout(2, 2));

        jLabel7.setText("Adresse SIP Proxy Server  :");
        jPanel23.add(jLabel7);

        proxySipAddressPortTextField.setText("5060");
        proxySipAddressPortTextField.setToolTipText("Port");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
                jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel19Layout.createSequentialGroup()
                                .addComponent(proxySipAddressIpTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(proxySipAddressPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel19Layout.setVerticalGroup(
                jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel19Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(proxySipAddressIpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(proxySipAddressPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel23.add(jPanel19);

        jLabel8.setText("Numéro :");
        jPanel23.add(jLabel8);

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
                jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(numberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
                jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel24Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(numberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel23.add(jPanel24);

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
                jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel22Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
                jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel22Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(148, Short.MAX_VALUE))
        );

        jPanel20.add(jPanel22, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Enregistrement", jPanel20);

        jPanel10.setLayout(new java.awt.BorderLayout());

        configureButton.setText("Configurer");
        configureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configure(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addContainerGap(302, Short.MAX_VALUE)
                                .addComponent(configureButton)
                                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(configureButton)
                                .addContainerGap())
        );

        jPanel10.add(jPanel11, java.awt.BorderLayout.PAGE_END);

        jPanel13.setLayout(new java.awt.GridLayout(2, 2));

        jLabel3.setText("Adresse SIP locale :");
        jPanel13.add(jLabel3);

        localSipAddressIpTextField.setToolTipText("IP");
        localSipAddressIpTextField.setEnabled(false);

        localSipAddressPortTextField.setText("6060");
        localSipAddressPortTextField.setToolTipText("Port");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
                jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(localSipAddressIpTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(localSipAddressPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel14Layout.setVerticalGroup(
                jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(localSipAddressIpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(localSipAddressPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        jPanel13.add(jPanel14);

        jLabel4.setText("Adresse RTP locale :");
        jPanel13.add(jLabel4);

        localRtpAddressIpTextField.setEnabled(false);

        localRtpAddressPortTextField.setText("10000");
        localRtpAddressPortTextField.setToolTipText("Port");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
                jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel15Layout.createSequentialGroup()
                                .addComponent(localRtpAddressIpTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(localRtpAddressPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel15Layout.setVerticalGroup(
                jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel15Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(localRtpAddressIpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(localRtpAddressPortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.add(jPanel15);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(116, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel12, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Configuration", jPanel2);

        jPanel16.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        jLabel5.setText("Messages recus");

        receivedMessagesTextArea.setRows(5);
        jScrollPane1.setViewportView(receivedMessagesTextArea);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
                jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel17Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 95, Short.MAX_VALUE))
                        .addComponent(jScrollPane1)
        );
        jPanel17Layout.setVerticalGroup(
                jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel17Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
        );

        jPanel16.add(jPanel17);

        jLabel6.setText("Messages envoyés");

        sentMessagesTextArea.setRows(5);
        jScrollPane2.setViewportView(sentMessagesTextArea);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
                jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel18Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
                jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel18Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
        );

        jPanel16.add(jPanel18);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jTabbedPane1.addTab("Log", jPanel3);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configure(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configure
        try {
            link = new SipLink(
                    localSipAddressIpTextField.getText(),
                    Integer.parseInt(localSipAddressPortTextField.getText()),
                    Integer.parseInt(localRtpAddressPortTextField.getText()),
                    this);
            disableConfiguration();
            callButton.setEnabled(true);
        } catch (InvalidArgumentException e) {
            e.printStackTrace();
            enableConfiguration();
            callButton.setEnabled(false);
        }
    }//GEN-LAST:event_configure

    private void call() {//GEN-FIRST:event_call
        if (callNumberTextField.getText().equals("")) {
            calleeAddress = SipLink.uriFromAddress(
                    destSipAddressIpTextField.getText(),
                    Integer.parseInt(destSipAddressPortTextField.getText())
            );
            link.call(calleeAddress);
        } else {
            link.callByNumber(callNumberTextField.getText());
        }


        establishing = true;

        callPanel.setVisible(false);
        callingPanel.setVisible(true);
        callActionsPanel.add(callingPanel, java.awt.BorderLayout.PAGE_END);
        callingContentLabel.setText("Etablissement de la connexion");

    }//GEN-LAST:event_call

    private void register() {
        String proxyAddress = SipLink.uriFromAddress(
                proxySipAddressIpTextField.getText(),
                Integer.parseInt(proxySipAddressPortTextField.getText())
        );
        link.register(proxyAddress, numberTextField.getText());
        disableRegistration();
    }

    private void registerService() {
        String address = SipLink.uriFromAddress(
                divertSipAddressIpTextField.getText(),
                Integer.parseInt(divertSipAddressPortTextField.getText())
        );
        link.registerService(address, divertConditionComboBox.getSelectedIndex() == 0);
        disableServiceRegistration();
    }

    private void cancelService() {
        link.cancelService();
        enableServiceRegistration();
    }

    public Boolean isCalling() {
        return calling;
    }

    public void ringing() {
        callingContentLabel.setText("Sonnerie...");
        playRinging();
        ringing = true;
    }

    private void hangUp() {
        incomingCallPanel.setVisible(false);
        callingPanel.setVisible(false);
        callPanel.setVisible(true);
        callActionsPanel.add(callPanel, java.awt.BorderLayout.PAGE_END);
        stopSound();
        if (calling) {
            link.endCall();
        } else if (establishing || ringing) {
            link.cancelCall();
        } else {
            link.hangUp();
        }
        resetState();
    }

    public void incomingCall(String from) {
        playRingtone();
        callPanel.setVisible(false);
        incomingCallPanel.setVisible(true);
        callActionsPanel.add(incomingCallPanel, java.awt.BorderLayout.PAGE_END);
        incomingCallContentLabel.setText(from);
    }

    public void answeredCall() {
        stopSound();
        calling = true;
        callingContentLabel.setText("Appel en cours...");
    }

    public void registrationFailed() {
        enableRegistration();
    }

    public void takeCall() {
        stopSound();
        link.takeCall();
        calling = true;
        incomingCallPanel.setVisible(false);
        callingPanel.setVisible(true);
        callActionsPanel.add(callingPanel, java.awt.BorderLayout.PAGE_END);
        callingContentLabel.setText("Appel en cours...");
    }

    public void cancelCall() {
        stopSound();
        incomingCallPanel.setVisible(false);
        callingPanel.setVisible(false);
        callPanel.setVisible(true);
        callActionsPanel.add(callPanel, java.awt.BorderLayout.PAGE_END);
        resetState();
    }

    private void resetState() {
        establishing = false;
        ringing = false;
        calling = false;
    }

    private void playRinging() {
        playSound(RINGING_MEDIA);
    }

    private void playRingtone() {
        playSound(RINGTONE_MEDIA);
    }

    private void playSound(String locator) {
        try {
            File soundFile = new File(locator);
            AudioInputStream audioIn = AudioSystem.getAudioInputStream(soundFile);
            clip = AudioSystem.getClip();
            clip.open(audioIn);
            clip.loop(Clip.LOOP_CONTINUOUSLY);
            clip.start();
        } catch (UnsupportedAudioFileException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (LineUnavailableException e) {
            e.printStackTrace();
        }
    }

    private void stopSound() {
        if (clip != null) {
            clip.stop();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SipPhone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SipPhone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SipPhone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SipPhone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SipPhone().setVisible(true);
            }
        });
    }

    private void enableConfiguration() {
        localSipAddressPortTextField.setEnabled(true);
        localRtpAddressPortTextField.setEnabled(true);
        configureButton.setEnabled(true);
    }

    private void enableRegistration() {
        proxySipAddressIpTextField.setEnabled(true);
        proxySipAddressPortTextField.setEnabled(true);
        numberTextField.setEnabled(true);
        proxyRegisterButton.setEnabled(true);
    }

    private void enableServiceRegistration() {
        divertConditionComboBox.setEnabled(true);
        divertSipAddressIpTextField.setEnabled(true);
        divertSipAddressPortTextField.setEnabled(true);
        registerServiceButton.setEnabled(true);
        cancelServiceButton.setEnabled(false);
    }

    private void disableConfiguration() {
        localSipAddressPortTextField.setEnabled(false);
        localRtpAddressPortTextField.setEnabled(false);
        configureButton.setEnabled(false);
    }

    private void disableRegistration() {
        proxySipAddressIpTextField.setEnabled(false);
        proxySipAddressPortTextField.setEnabled(false);
        numberTextField.setEnabled(false);
        proxyRegisterButton.setEnabled(false);
    }

    private void disableServiceRegistration() {
        divertConditionComboBox.setEnabled(false);
        divertSipAddressIpTextField.setEnabled(false);
        divertSipAddressPortTextField.setEnabled(false);
        registerServiceButton.setEnabled(false);
        cancelServiceButton.setEnabled(true);
    }

    public void addReceivedMessage(String receivedMessage) {
        receivedMessagesTextArea.setText(receivedMessagesTextArea.getText() + receivedMessage + "\n");
    }

    public void addSentMessage(String sentMessage) {
        sentMessagesTextArea.setText(sentMessagesTextArea.getText() + sentMessage + "\n");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton callButton;
    private javax.swing.JButton hangupButton;
    private javax.swing.JButton takeCallButton;
    private javax.swing.JButton endCallButton;
    private javax.swing.JButton configureButton;
    private javax.swing.JLabel incomingCallContentLabel;
    private javax.swing.JLabel callingContentLabel;
    private javax.swing.JTextField destRtpAddressIpTextField;
    private javax.swing.JTextField destRtpAddressPortTextField;
    private javax.swing.JTextField destSipAddressIpTextField;
    private javax.swing.JTextField destSipAddressPortTextField;
    private javax.swing.JLabel contentLabel;
    private javax.swing.JComboBox<String> divertConditionComboBox;
    private javax.swing.JTextField divertSipAddressIpTextField;
    private javax.swing.JTextField divertSipAddressPortTextField;
    private javax.swing.JButton cancelServiceButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel callActionsPanel;
    private javax.swing.JPanel callPanel;
    private javax.swing.JPanel callingPanel;
    private javax.swing.JPanel incomingCallPanel;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField localRtpAddressIpTextField;
    private javax.swing.JTextField localRtpAddressPortTextField;
    private javax.swing.JTextField localSipAddressIpTextField;
    private javax.swing.JTextField localSipAddressPortTextField;
    private javax.swing.JTextField numberTextField;
    private javax.swing.JTextField callNumberTextField;
    private javax.swing.JButton proxyRegisterButton;
    private javax.swing.JTextField proxySipAddressIpTextField;
    private javax.swing.JTextField proxySipAddressPortTextField;
    private javax.swing.JTextArea receivedMessagesTextArea;
    private javax.swing.JTextArea sentMessagesTextArea;
    private javax.swing.JButton registerServiceButton;
    // End of variables declaration//GEN-END:variables
}
